export const searchOptions = [
  ["DIA", "Dow Jones Industrial Average"],
  ["SPY", "SPDR S&P 500 ETF Trust"],
  ["QQQ", "Invesco QQQ Trust"],
  ["EWC", "iShares MSCI Canada ETF"],
  ["FEZ", "SPDR EURO STOXX 50 ETF"],
  ["EWG", "iShares MSCI Germany ETF"],
  ["EWU", "iShares MSCI United Kingdom ETF"],
  ["EWQ", "iShares MSCI France ETF"],
  ["EWI", "iShares MSCI Italy ETF"],
  ["EWL", "iShares MSCI Switzerland ETF"],
  ["EWJ", "iShares MSCI Japan ETF"],
  ["FLCH", "Franklin FTSE China ETF"],
  ["EWA", "iShares MSCI Australia ETF"],
  ["EWH", "iShares MSCI Hong Kong ETF"],
  ["EWT", "iShares MSCI Taiwan ETF"],
  ["EWS", "iShares MSCI Singapore ETF"],
  ["EWY", "iShares MSCI South Korea ETF"],
  ["USO", "United States Oil Fund"],
  ["UNG", "United States Natural Gas Fund"],
  ["BNO", "United States Brent Oil Fund"],
  ["UGA", "United States Gasoline Fund"],
  ["GLD", "SPDR Gold Shares"],
  ["SLV", "iShares Silver Trust"],
  ["PALL", "ETFS Physical Palladium Shares"],
  ["PLAT", "ETFS Physical Platinum Shares"],
  ["CPER", "United States Copper Fund"],
  ["LIT", "Global X Lithium & Battery Tech ETF"],
  ["WEAT", "Teucrium Wheat Fund"],
  ["CORN", "Teucrium Corn Fund"],
  ["SOYB", "Teucrium Soybean Fund"],
  ["NIB", "iPath Bloomberg Cocoa"],
  ["CANE", "Teucrium Sugar Fund"],
  ["COW", "ProShares Ultra Bloomberg Livestock"],
];
